### PR TITLE
Make new version compatible

### PR DESCRIPTION
**Pull request by xepozz**
# The problem

`ReflectionClosure::getCode()` in `3.x` versions returns `raw function code`, but backward compatibility was broken in `4.x` branch. 
`ReflectionClosure::getCode()` in `4.x` branch now returns `<?php {use statements} raw function code`. 
I've tried to fix this and made a test case for testing compatibility with previous major version.

### Test case

```php
<?php

declare(strict_types=1);

namespace Opis\Closure\Test;

use Opis\Closure\ReflectionClosure;
use PHPUnit\Framework\TestCase;

class CompatibleTest extends TestCase
{
    public function testCompatible()
    {
        $fn = fn (MyInterface $arg): int => 1;
        $ref = new ReflectionClosure($fn);
        $code = $ref->getCode();

        $this->assertEquals('fn (MyInterface $arg): int => 1', $code);
    }
}

```

### Branch `4.x`:
```
1) Opis\Closure\Test\CompatibleTest::testCompatible
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'fn (MyInterface $arg): int => 1'
+'<?php\n
+namespace Opis\Closure\Test;\n
+return fn (MyInterface $arg): int => 1;'

/home/xepozz/PhpstormProjects/closure/tests/CompatibleTest.php:18
```

### Pull request's branch
```
OK (1 test, 1 assertion)
```

### Master branch
```
1) Opis\Closure\Test\CompatibleTest::testCompatible
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'fn (MyInterface $arg): int => 1'
+'fn (\Opis\Closure\Test\MyInterface $arg): int => 1'

/home/xepozz/PhpstormProjects/closure/tests/CompatibleTest.php:15
```

### New problem
As you can see `3.0` versions rightly add the namespace part to class/function/constant name.
For example, see to results of testing run on `master` branch above:
`fn (MyInterface $arg)` => `fn (\Opis\Closure\Test\MyInterface $arg)` and other cases

### My proposal

Merge this branch into `4.x` branch.
Anyone who knows parsing more than I will add this compatible omission.

I've created [issue](https://github.com/opis/closure/issues/68) for fixing the new problem

### CODE REVIEW

**Comment by msarca** [comment]
ReflectionClosure [is internal](https://github.com/opis/closure/blob/4.x/src/ReflectionClosure.php#L23). It's not part of the public API.

**Comment by xepozz** [comment]
@msarca So the feature getting function source code will unavailable?
It's a useful and required part for https://github.com/yiisoft/composer-config-plugin
In this case we need to write our own implementation...

**Comment by xepozz** [comment]
So what about to merge some improvements like in `src/ClosureStream.php`?

**Comment by msarca** [comment]
The scope of the library is to serialize closures and nothing more. Using the library outside of its scope is on your own risk. If you're not using this library exclusively for closure serialization, I would highly recommend to search for an alternative solution. As for the improvements, I would suggest you to rather open an issue first instead of submitting a PR.

**Pull request closed without merging**
