### PR TITLE
Update LICENSE year

### PR DESCRIPTION
**Pull request by BraxtonFair**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎 There have been no commits made in 2017.

**Comment by msarca** [comment]
@GrahamCampbell Actually, a new version is ready to be released the following week and it was committed in 2017. Anyhow, this pull request is more than welcome since people need to know that this project is, was and it will be maintained in the future and that I will continue to provide support for those who are requesting it. @BraxtonFair Thank you. I was so focused on providing new features and I totally forgot about this file.

**Comment by BraxtonFair** [comment]
No problem!

**Comment by GrahamCampbell** [comment]
Ah, at the time, there were no commits made to master, which is where this PR was sent.

**Pull request merged**
