### PR TITLE
Release v3.6.0

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I propose we tag v3.6.0 on Monday next week (12th October 2020).

### CODE REVIEW

**Comment by msarca** [comment]
We had a crazy week/month at work and it's not over yet. Sorry for the radio silence. No objections on our side.

**Comment by GrahamCampbell** [comment]
No need to apologise. :)

**Comment by aliwesome** [comment]
We still facing this issue:
"Unbinding $this of closure is deprecated"

https://github.com/opis/closure/blob/master/src/SerializableClosure.php#L263

**Comment by GrahamCampbell** [comment]
@aliwesome You have two options here. Either, you can submit a PR fixing the bug you are experiencing, or you can pay for someone to allocate time to fix the bug. Posting duplicate comments won't help fix the issue any faster, I'm afraid.

**Comment by aliwesome** [comment]
I did not post this comment just for mentioning the bug, but also I did this to gather more information and help to fix it.

**Pull request merged**
