### PR TITLE
Fix PSR-4 class names

### PR DESCRIPTION
**Pull request by williamdes**
Found in Debian: https://bugs.debian.org/1039811

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, though this change doesn't matter since these are just tests.

**Comment by GrahamCampbell** [comment]
The fact that debian are choosing to use their own phpunit instead of using the one the project says it supports is the issue here.

**Comment by williamdes** [comment]
Please re open this PR and consider reading the actual change
this is non sense replying...
Deceiving @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Like I said, the bug is in Debian. Our test suite cannot be run on phpunit 10. We control how our tests are run, in our own composer.json.

**Comment by williamdes** [comment]
And THIS HAS NOTTHING TO DO WITH Debian.
Use normal phpunit and it gives thee same results

**Comment by williamdes** [comment]
> Like I said, the bug is in Debian. Our test suite cannot be run on phpunit 10. We control how our tests are run, in our own composer.json. Using a global copy of phpunit is a huge mistake.

This is false. It runs perfectly on phpunit 10, just two psr-4 warnings

**Comment by williamdes** [comment]
Even composer will be unhappy with non psr-4 compliant classes. This is so much obvious that my change has nothing to do with Debian or phpunit.
It's basics psr-4 compliance..

**Pull request closed without merging**
