### PR TITLE
Fix PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by kylekatarnls**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
That is not enough. The 3.x branch won't work on PHP 8.1 without major changes.

**Comment by Ghostff** [comment]
There is no fix for Serializable being deprecated?

**Comment by garciasdos** [comment]
> There is no fix for Serializable being deprecated?

Same question here, hope there's a fix soon 🤞🏼

**Comment by GrahamCampbell** [comment]
Correct, there is no fix. This is not the only issue you will encounter. Only the new beta version of this package will work with PHP 8.1. Alternatively, Laravel now has a fork that works on PHP 7.4-8.1. It was necessary to drop PHP 7.3 and earlier to enable PHP 8.1 support. https://github.com/laravel/serializable-closure

**Pull request closed without merging**
